# Generated by Django 4.1 on 2022-12-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Georgi', max_length=25),
            preserve_default=False,
        ),
    ]
