# Generated by Django 4.1 on 2022-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_options_remove_appuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
