# Generated by Django 4.1 on 2022-12-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appuser_city_appuser_fist_name_appuser_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
