# Generated by Django 4.1 on 2022-12-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email has been used from another user ,please enter a different email.'}, max_length=254, unique=True),
        ),
    ]
