# Generated by Django 4.1 on 2022-12-05 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('cart', '0003_remove_cartitem_cart_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Order',
        ),
    ]
