# Generated by Django 4.1 on 2022-12-17 20:44

import ProjectDefence.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='first_name',
            field=models.CharField(max_length=10, validators=[ProjectDefence.accounts.validators.check_name_contains_only_letters]),
        ),
    ]
