# Generated by Django 4.1 on 2022-12-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
