# Generated by Django 4.1 on 2022-12-04 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Console', 'Console')], max_length=25)),
                ('name', models.CharField(max_length=25, null=True)),
                ('make', models.CharField(max_length=25)),
                ('price', models.FloatField(max_length=25, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.URLField()),
                ('specifications', models.TextField()),
            ],
        ),
    ]
