# Generated by Django 4.1 on 2022-12-17 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, max_length=25, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
